### ISSUE TITLE
Generated docs.yaml - eliminate duplicate keys

### ISSUE THREAD

**Issue by zambrovski** [holisticon/camunda-bpm-swagger#17]
https://github.com/holisticon/camunda-bpm-swagger/blob/74575f8c137cd2ab9fb3f4b2dbcbbc80f4e6b564/extension/rest-docs/src/main/java/org/camunda/bpm/swagger/docs/DocumentationYaml.java#L34

Strange behaviour, the keymapper function in line 34 delivers the duplicate key. The code below works... 
What is the problem here?

**Comment by jangalinski** [comment]
ich staune nicht ... es gibt duplicate keys ...

siehe

this.operations = new HashMap<>();
List<String> errors = new ArrayList<>();

for (final RestOperation r : items.getRestOperations()) {
Pair<String, String> key = Pair.of(r.getPath(), r.getMethod());

if (operations.containsKey(key)) {
errors.add("duplicate key: " + key);
}
operations.put(key, r);
}
if (!errors.isEmpty()) {
throw new IllegalStateException("error: " + errors);
}

liefert:

java.lang.IllegalStateException: error: [
duplicate key: (/case-instance/count,POST), 
duplicate key: (/job/suspended,PUT), 
duplicate key: (/job/suspended,PUT), 
duplicate key: (/job/suspended,PUT), 
duplicate key: (/job-definition/suspended,PUT), 
duplicate key: (/process-instance/suspended,PUT), 
duplicate key: (/process-instance/{id}/variables/{varName}/data,POST)]

da ist collect strikt, der normale loop überschreibt einfach nur immer wieder den key.
