### ISSUE TITLE
Generate DTO Annotations with spoon.

### ISSUE THREAD

**Issue by zambrovski** [holisticon/camunda-bpm-swagger#24]
The inheritance in DTOs seemd to fail, so we need original DTOs to be annotated with Swagger Annotations. 

Use Spoon processing to write files with annotations with information from yaml

**Comment by jangalinski** [comment]
information from yaml is missing ... how can I get it? Otherwise, the dtos are generated with empty annotations.

**Comment by zambrovski** [comment]
We still create CamundaDTO objects and pass the information inside. The idea is to collect them in model repository, but not for generation but for the information step. 

If it is too strange, just generate empty annotations....

**Comment by jangalinski** [comment]
I will close this one, because the main part "annotating camunda dtos with apiModel/Property" works. Will create a follow up for enriching the dto with more metadata read during swagger-service processing.
