### ISSUE TITLE
Fix m issing methods in SpringBoot

### ISSUE THREAD

**Issue by zambrovski** [holisticon/camunda-bpm-swagger#33]
Currently, if the generated sswagger.json is deployed using the SpringBoot example, some methods are missing. 

Investigate what happens there (the same swagger.json works fine in WildFly) and fix the issue. By doing so, make sure the static content of the swagger ui is pulled from the swagger-ui webjar and is not provided inside of the example's static content folder.

**Comment by jangalinski** [comment]
switched to webjar, see 281599f9d62bdb35448d31a2cf9e3bbe3c213740

**Comment by jangalinski** [comment]
@zambrovski : please check if the methods are there now, you know better what to look for

**Comment by zambrovski** [comment]
No missing methods related to spring-boot anymore. Thank you @jangalinski
